sudo: required
services:
  - docker

before_install:
  - docker build -t andreatrash78/docker-react -f ./client/Dockerfile.dev ./client/Dockerfile.dev .

script:
  - docker run -e CI=true andreatrash78/docker-react npm test

after_success:
  - docker build -t andreatrash78/multi-client ./client
  - docker build -t andreatrash78/multi-nginx ./nginx
  - docker build -t andreatrash78/multi-server ./server
  - docker build -t andreatrash78/multi-worker ./worker
# Log in to docker CLI
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push andreatrash78/multi-client
  - docker push andreatrash78/multi-nginx
  - docker push andreatrash78/multi-server
  - docker push andreatrash78/multi-worker

